apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: gksample
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        image: mysql:latest
        name: mysql
        ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
