apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-app
  namespace: gksample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: pbuggaveeti/pysample:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
